version: '3'
services:
  app_main:
    # build: .
    image: jilvo/snowy-buy-bot:1.2.3
    command: ["python", "bot_telegram/main.py"]
    ports:
      - "4000:80"
    volumes:
      - ./medias:/app/medias

  app_send_message:
    # build: .
    image: jilvo/snowy-buy-bot:1.2.3
    command: ["python", "bot_telegram/main_send_message.py"]
    ports:
      - "4001:80"
    volumes:
      - ./medias:/app/medias
  app_trending:
    # build: .
    image: jilvo/snowy-buy-bot:1.2.3
    command: ["python", "bot_telegram/main_trending.py"]
    ports:
      - "4002:80"

  app_subscription:
    image: jilvo/snowy-buy-bot:1.2.3
    command: ["python", "bot_telegram/main_subscription.py"]
    ports:
      - "4003:80"

