version: '3'
services:
  app_main:
    # build: .
    image: jilvo/snowy-buy-bot:1.0.11
    command: ["python", "bot_telegram/main.py"]
    ports:
      - "4000:80"
    volumes:
      - ./medias:/app/medias

  app_send_message:
    # build: .
    image: jilvo/snowy-buy-bot:1.0.11
    command: ["python", "bot_telegram/main_send_message.py"]
    ports:
      - "4001:80"
    volumes:
      - ./medias:/app/medias

